# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PetFinder' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PetFinder
    pod 'SwiftyUserDefaults'
    pod 'Alamofire'
    pod 'RappleProgressHUD'
    pod 'SwiftQRCode'
    pod 'IQKeyboardManagerSwift'
    pod 'AVReachability'
    pod 'SCLAlertView'

  target 'PetFinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PetFinderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
